In [175]:
import pandas as pd

In [176]:
df = pd.read_csv("raw_data.csv")
df

/var/folders/7k/dkrw1dkn70xb44njcjrldx2w0000gn/T/ipykernel_23180/2323030985.py:1: DtypeWarning: Columns (18,20,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("raw_data.csv")

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,64416080,03/21/2025 01:05:09 AM,03/21/2025 01:24:30 AM,NYPD,New York City Police Department,Noise - Vehicle,Engine Idling,Street/Sidewalk,11237.0,240 STARR STREET,...,Truck,NaN,NaN,NaN,NaN,NaN,NaN,40.705636,-73.922603,"(40.70563553927927, -73.9226025936758)"
1,64416159,03/21/2025 12:44:21 AM,03/21/2025 01:11:54 AM,NYPD,New York City Police Department,Noise - Vehicle,Engine Idling,Street/Sidewalk,11236.0,10307 FLATLANDS AVENUE,...,Truck,NaN,NaN,NaN,NaN,NaN,NaN,40.646734,-73.895922,"(40.64673356570643, -73.89592158520432)"
2,64411272,03/21/2025 12:41:50 AM,03/21/2025 12:54:01 AM,NYPD,New York City Police Department,Noise - Vehicle,Engine Idling,Street/Sidewalk,10011.0,525 WEST 24 STREET,...,Truck,NaN,NaN,NaN,NaN,NaN,NaN,40.748861,-74.004861,"(40.74886117774447, -74.00486145386272)"
3,64416160,03/20/2025 11:55:44 PM,03/21/2025 12:27:14 AM,NYPD,New York City Police Department,Noise - Vehicle,Engine Idling,Street/Sidewalk,11428.0,91-34 221 PLACE,...,Truck,NaN,NaN,NaN,NaN,NaN,NaN,40.726530,-73.737569,"(40.726530091644584, -73.7375690678977)"
4,64416079,03/20/2025 11:37:59 PM,03/21/2025 12:35:46 AM,NYPD,New York City Police Department,Noise - Vehicle,Engine Idling,Street/Sidewalk,11237.0,240 STARR STREET,...,Truck,NaN,NaN,NaN,NaN,NaN,NaN,40.705636,-73.922603,"(40.70563553927927, -73.9226025936758)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138188,29616087,01/01/2015 02:47:32 PM,01/01/2015 03:28:36 PM,NYPD,New York City Police Department,Noise - Vehicle,Engine Idling,Street/Sidewalk,11412.0,114-71 DUNKIRK STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.695192,-73.767793,"(40.69519207414092, -73.76779342277058)"
138189,29618448,01/01/2015 01:10:23 PM,01/01/2015 01:29:00 PM,NYPD,New York City Police Department,Noise - Vehicle,Engine Idling,Street/Sidewalk,11236.0,GLENWOOD ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.651857,-73.892057,"(40.65185726253694, -73.89205747028711)"
138190,29615061,01/01/2015 01:06:00 PM,01/07/2015 03:45:00 PM,DEP,Department of Environmental Protection,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",NaN,11236.0,1090 GLENWOOD ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.651857,-73.892057,"(40.65185726253694, -73.89205747028711)"
138191,29616054,01/01/2015 12:42:04 PM,01/01/2015 02:07:18 PM,NYPD,New York City Police Department,Noise - Vehicle,Engine Idling,Street/Sidewalk,11201.0,187 HICKS STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.696019,-73.995478,"(40.696019108171626, -73.99547777920839)"
138192,29616807,01/01/2015 09:16:00 AM,01/07/2015 08:00:00 AM,DEP,Department of Environmental Protection,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",NaN,11231.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.676710,-74.004762,"(40.67670963418922, -74.00476245934685)"

In [177]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138193 entries, 0 to 138192
Data columns (total 41 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Unique Key                      138193 non-null  int64
 1   Created Date                    138193 non-null  object
 2   Closed Date                     137925 non-null  object
 3   Agency                          138193 non-null  object
 4   Agency Name                     138193 non-null  object
 5   Complaint Type                  138193 non-null  object
 6   Descriptor                      138193 non-null  object
 7   Location Type                   91887 non-null   object
 8   Incident Zip                    137863 non-null  float64
 9   Incident Address                126174 non-null  object
 10  Street Name                     126174 non-null  object
 11  Cross Street 1                  127426 non-null  object
 12  Cross Street 2                  127384 non-null  object
 13  Intersection Street 1           75231 non-null   object
 14  Intersection Street 2           75208 non-null   object
 15  Address Type                    112611 non-null  object
 16  City                            128526 non-null  object
 17  Landmark                        53521 non-null   object
 18  Facility Type                   30055 non-null   object
 19  Status                          138193 non-null  object
 20  Due Date                        30658 non-null   object
 21  Resolution Description          138083 non-null  object
 22  Resolution Action Updated Date  138020 non-null  object
 23  Community Board                 138187 non-null  object
 24  BBL                             108284 non-null  float64
 25  Borough                         138187 non-null  object
 26  X Coordinate (State Plane)      136444 non-null  float64
 27  Y Coordinate (State Plane)      136458 non-null  float64
 28  Open Data Channel Type          138193 non-null  object
 29  Park Facility Name              138193 non-null  object
 30  Park Borough                    138187 non-null  object
 31  Vehicle Type                    12992 non-null   object
 32  Taxi Company Borough            0 non-null       float64
 33  Taxi Pick Up Location           0 non-null       float64
 34  Bridge Highway Name             0 non-null       float64
 35  Bridge Highway Direction        0 non-null       float64
 36  Road Ramp                       0 non-null       float64
 37  Bridge Highway Segment          0 non-null       float64
 38  Latitude                        136444 non-null  float64
 39  Longitude                       136444 non-null  float64
 40  Location                        136444 non-null  object
dtypes: float64(12), int64(1), object(28)
memory usage: 43.2+ MB

In [178]:
## Convert zip code column to strings, right now it is number
df["Incident Zip"].astype(str)

0         11237.0
1         11236.0
2         10011.0
3         11428.0
4         11237.0
           ...
138188    11412.0
138189    11236.0
138190    11236.0
138191    11201.0
138192    11231.0
Name: Incident Zip, Length: 138193, dtype: object

In [179]:
columns_to_display = ["Created Date", "Complaint Type", "Descriptor", "Incident Zip", "City", "Borough", "Vehicle Type"]

In [180]:
df[columns_to_display]

,Created Date,Complaint Type,Descriptor,Incident Zip,City,Borough,Vehicle Type
0,03/21/2025 01:05:09 AM,Noise - Vehicle,Engine Idling,11237.0,BROOKLYN,BROOKLYN,Truck
1,03/21/2025 12:44:21 AM,Noise - Vehicle,Engine Idling,11236.0,BROOKLYN,BROOKLYN,Truck
2,03/21/2025 12:41:50 AM,Noise - Vehicle,Engine Idling,10011.0,NEW YORK,MANHATTAN,Truck
3,03/20/2025 11:55:44 PM,Noise - Vehicle,Engine Idling,11428.0,QUEENS VILLAGE,QUEENS,Truck
4,03/20/2025 11:37:59 PM,Noise - Vehicle,Engine Idling,11237.0,BROOKLYN,BROOKLYN,Truck
...,...,...,...,...,...,...,...
138188,01/01/2015 02:47:32 PM,Noise - Vehicle,Engine Idling,11412.0,SAINT ALBANS,QUEENS,NaN
138189,01/01/2015 01:10:23 PM,Noise - Vehicle,Engine Idling,11236.0,BROOKLYN,BROOKLYN,NaN
138190,01/01/2015 01:06:00 PM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11236.0,BROOKLYN,BROOKLYN,NaN
138191,01/01/2015 12:42:04 PM,Noise - Vehicle,Engine Idling,11201.0,BROOKLYN,BROOKLYN,NaN
138192,01/01/2015 09:16:00 AM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11231.0,BROOKLYN,BROOKLYN,NaN

In [181]:
type(df[columns_to_display])

pandas.core.frame.DataFrame

In [182]:
df[columns_to_display]["Incident Zip"].value_counts()

Incident Zip
10036.0    12021
10019.0     5469
11366.0     3082
11201.0     2796
11385.0     2384
           ...
10153.0        1
10055.0        1
10152.0        1
10048.0        1
10171.0        1
Name: count, Length: 204, dtype: int64

In [183]:
## Top 2 zip codes with highest idling complaints in this time period- Fresh Meadows, Glendale/Ridgewood
df[columns_to_display].query("Borough == 'QUEENS'")["Incident Zip"].value_counts()

Incident Zip
11366.0    3082
11385.0    2383
11375.0    1591
11101.0    1232
11105.0    1230
           ...
11430.0       8
11005.0       4
11697.0       2
11208.0       2
11237.0       1
Name: count, Length: 66, dtype: int64

In [184]:
## Top 2 zip codes with highest idling complaints in this time period- Downtown Brooklyn/Dumbo/Cobble Hill, Greenpoint
df[columns_to_display].query("Borough == 'BROOKLYN'")["Incident Zip"].value_counts()

Incident Zip
11201.0    2796
11222.0    2208
11211.0    1925
11215.0    1839
11205.0    1557
11230.0    1462
11238.0    1383
11206.0    1366
11218.0    1317
11209.0    1301
11249.0    1288
11220.0    1200
11237.0    1138
11226.0    1121
11231.0    1098
11235.0    1073
11234.0    1062
11221.0    1028
11217.0     972
11212.0     908
11229.0     867
11216.0     830
11204.0     742
11232.0     706
11203.0     679
11208.0     658
11214.0     638
11223.0     628
11225.0     571
11210.0     510
11219.0     481
11207.0     480
11236.0     445
11228.0     399
11213.0     397
11233.0     347
11224.0     262
11239.0     107
11385.0       1
Name: count, dtype: int64

In [185]:
## Top 2 zip codes with highest idling complaints in this time period- Riverdale/Kingsbridge, Highbridge
df[columns_to_display].query("Borough == 'BRONX'")["Incident Zip"].value_counts()

Incident Zip
10463.0    1413
10452.0    1165
10467.0     875
10462.0     753
10461.0     638
10473.0     620
10469.0     604
10458.0     565
10466.0     538
10456.0     492
10453.0     478
10468.0     451
10472.0     432
10457.0     416
10465.0     336
10451.0     330
10471.0     330
10460.0     288
10455.0     270
10459.0     246
10454.0     210
10474.0     163
10470.0     146
10464.0     115
10475.0     102
11102.0       7
11105.0       5
11103.0       3
11370.0       1
Name: count, dtype: int64

In [186]:
## Top 2 zip codes with highest idling complaints in this time period- Midtown
df[columns_to_display].query("Borough == 'MANHATTAN'")["Incident Zip"].value_counts()

Incident Zip
10036.0    12021
10019.0     5469
10002.0     1939
10025.0     1926
10003.0     1912
           ...
10153.0        1
10048.0        1
10121.0        1
10171.0        1
10123.0        1
Name: count, Length: 66, dtype: int64

In [187]:
df[columns_to_display].query("Borough == 'STATEN ISLAND'")["Incident Zip"].value_counts()

Incident Zip
10314.0    1032
10312.0     702
10301.0     654
10306.0     627
10304.0     451
10305.0     383
10308.0     317
10303.0     270
10309.0     251
10310.0     244
10302.0     199
10307.0      59
Name: count, dtype: int64

In [209]:
## list of top 2 zip codes with highest idling complaints in each borough
top_zips = ["11366.0", "11385.0", "11201.0", "11222.0", "10463.0", "10452.0", "10036.0", "10019.0", "10314.0", "10312.0"]
top_zips

['11366.0',
 '11385.0',
 '11201.0',
 '11222.0',
 '10463.0',
 '10452.0',
 '10036.0',
 '10019.0',
 '10314.0',
 '10312.0']

In [221]:
## first convert zip codes to string from numerical value, then filter the df for the top 2 zip codes using the list created above
df['Incident Zip'] = df['Incident Zip'].astype(str)
df[columns_to_display].query("`Incident Zip` in @top_zips")

,Created Date,Complaint Type,Descriptor,Incident Zip,City,Borough,Vehicle Type
5,03/20/2025 11:10:54 PM,Noise - Vehicle,Engine Idling,11201.0,BROOKLYN,BROOKLYN,Car
9,03/20/2025 09:44:18 PM,Noise - Vehicle,Engine Idling,10314.0,STATEN ISLAND,STATEN ISLAND,Car
12,03/20/2025 07:54:05 PM,Noise - Vehicle,Engine Idling,10463.0,BRONX,BRONX,Car
14,03/20/2025 04:44:00 PM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",10036.0,NEW YORK,MANHATTAN,NaN
15,03/20/2025 04:44:00 PM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",10036.0,NEW YORK,MANHATTAN,NaN
...,...,...,...,...,...,...,...
138161,01/04/2015 09:01:28 AM,Noise - Vehicle,Engine Idling,11201.0,BROOKLYN,BROOKLYN,NaN
138162,01/03/2015 10:49:48 PM,Noise - Vehicle,Engine Idling,10036.0,NEW YORK,MANHATTAN,NaN
138164,01/03/2015 07:50:27 PM,Noise - Vehicle,Engine Idling,11201.0,BROOKLYN,BROOKLYN,NaN
138173,01/02/2015 09:57:00 PM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11201.0,BROOKLYN,BROOKLYN,NaN
138191,01/01/2015 12:42:04 PM,Noise - Vehicle,Engine Idling,11201.0,BROOKLYN,BROOKLYN,NaN

In [251]:
##  filtering for only queens each top 2 zips to see count of vehicle types 
df['Incident Zip'] = df['Incident Zip'].astype(str)
df[columns_to_display].query("`Incident Zip` == '11366.0'")

,Created Date,Complaint Type,Descriptor,Incident Zip,City,Borough,Vehicle Type
611,03/06/2025 11:38:00 AM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11366.0,QUEENS,QUEENS,NaN
2780,01/07/2025 01:18:57 PM,Noise - Vehicle,Engine Idling,11366.0,FRESH MEADOWS,QUEENS,Other
3359,12/21/2024 01:05:00 PM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11366.0,QUEENS,QUEENS,NaN
7771,09/01/2024 04:14:25 PM,Noise - Vehicle,Engine Idling,11366.0,NaN,QUEENS,Car
8054,08/26/2024 01:00:48 AM,Noise - Vehicle,Engine Idling,11366.0,NaN,QUEENS,Car
...,...,...,...,...,...,...,...
133631,07/23/2015 01:00:00 PM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11366.0,Fresh Meadows,QUEENS,NaN
133990,07/07/2015 05:08:00 PM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11366.0,Fresh Meadows,QUEENS,NaN
135048,05/22/2015 02:45:00 PM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11366.0,Fresh Meadows,QUEENS,NaN
136261,04/05/2015 06:02:02 PM,Noise - Vehicle,Engine Idling,11366.0,FRESH MEADOWS,QUEENS,NaN
136707,03/18/2015 02:22:00 PM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11366.0,Fresh Meadows,QUEENS,NaN

In [257]:
## FRESH MEADOWS
df[columns_to_display].query("`Incident Zip` == '11366.0'").value_counts("Descriptor")

Descriptor
Engine Idling                            1797
Air: Odor/Fumes, Vehicle Idling (AD3)    1284
Idling or Blocking Traffic                  1
Name: count, dtype: int64

In [261]:
df[columns_to_display].query("`Incident Zip` == '11366.0'").value_counts("Vehicle Type")

Vehicle Type
Other    45
Car       8
Truck     2
Van       1
Name: count, dtype: int64

In [269]:
df[columns_to_display].query("`Incident Zip` == '11385.0'")

,Created Date,Complaint Type,Descriptor,Incident Zip,City,Borough,Vehicle Type
111,03/18/2025 05:48:50 PM,Noise - Vehicle,Engine Idling,11385.0,RIDGEWOOD,QUEENS,Car
121,03/18/2025 11:51:20 AM,Noise - Vehicle,Engine Idling,11385.0,RIDGEWOOD,QUEENS,Car
167,03/17/2025 08:06:55 AM,Noise - Vehicle,Engine Idling,11385.0,RIDGEWOOD,QUEENS,Car
172,03/17/2025 01:09:44 AM,Noise - Vehicle,Engine Idling,11385.0,RIDGEWOOD,QUEENS,Car
283,03/14/2025 09:59:00 AM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11385.0,RIDGEWOOD,QUEENS,NaN
...,...,...,...,...,...,...,...
137508,02/09/2015 05:58:00 AM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11385.0,Ridgewood,QUEENS,NaN
137556,02/06/2015 06:21:00 AM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11385.0,Ridgewood,QUEENS,NaN
137710,01/28/2015 11:13:44 PM,Noise - Vehicle,Engine Idling,11385.0,RIDGEWOOD,QUEENS,NaN
137735,01/27/2015 02:48:00 PM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11385.0,Ridgewood,QUEENS,NaN
137744,01/26/2015 11:40:41 PM,Noise - Vehicle,Engine Idling,11385.0,RIDGEWOOD,QUEENS,NaN

In [265]:
## RIDGEWOOD
df[columns_to_display].query("`Incident Zip` == '11385.0'").value_counts("Descriptor")

Descriptor
Engine Idling                            1918
Air: Odor/Fumes, Vehicle Idling (AD3)     462
Idling or Blocking Traffic                  4
Name: count, dtype: int64

In [271]:
df[columns_to_display].query("`Incident Zip` == '11385.0'").value_counts("Vehicle Type")

Vehicle Type
Car      74
Other    40
Truck    18
Van       7
SUV       4
Name: count, dtype: int64

In [275]:
## Same with Brooklyn neighborhoods
df[columns_to_display].query("`Incident Zip` == '11201.0'")

,Created Date,Complaint Type,Descriptor,Incident Zip,City,Borough,Vehicle Type
5,03/20/2025 11:10:54 PM,Noise - Vehicle,Engine Idling,11201.0,BROOKLYN,BROOKLYN,Car
81,03/19/2025 09:29:00 AM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11201.0,BROOKLYN,BROOKLYN,NaN
84,03/19/2025 08:26:00 AM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11201.0,BROOKLYN,BROOKLYN,NaN
106,03/18/2025 08:00:12 PM,Noise - Vehicle,Engine Idling,11201.0,BROOKLYN,BROOKLYN,Car
144,03/17/2025 07:33:00 PM,Noise - Vehicle,Engine Idling,11201.0,BROOKLYN,BROOKLYN,Car
...,...,...,...,...,...,...,...
138128,01/06/2015 11:02:40 AM,Noise - Vehicle,Engine Idling,11201.0,BROOKLYN,BROOKLYN,NaN
138161,01/04/2015 09:01:28 AM,Noise - Vehicle,Engine Idling,11201.0,BROOKLYN,BROOKLYN,NaN
138164,01/03/2015 07:50:27 PM,Noise - Vehicle,Engine Idling,11201.0,BROOKLYN,BROOKLYN,NaN
138173,01/02/2015 09:57:00 PM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11201.0,BROOKLYN,BROOKLYN,NaN
138191,01/01/2015 12:42:04 PM,Noise - Vehicle,Engine Idling,11201.0,BROOKLYN,BROOKLYN,NaN

In [281]:
## city only says brooklyn here but this zip code is for DUMBO, downtown brooklyn and cobble hill 
df[columns_to_display].query("`Incident Zip` == '11201.0'").value_counts("City")

City
BROOKLYN    2712
Name: count, dtype: int64

In [285]:
## has 4 'no idling' which are complaints about the sign, not actual idling- so total complaints should be counted as 2792
df[columns_to_display].query("`Incident Zip` == '11201.0'").value_counts("Descriptor")

Descriptor
Engine Idling                            1960
Air: Odor/Fumes, Vehicle Idling (AD3)     830
No Idling                                   4
Idling or Blocking Traffic                  2
Name: count, dtype: int64

In [289]:
df[columns_to_display].query("`Incident Zip` == '11201.0'").value_counts("Vehicle Type")

Vehicle Type
Car      106
Truck     55
Other     36
Van        4
SUV        1
Name: count, dtype: int64

In [293]:
df[columns_to_display].query("`Incident Zip` == '11222.0'")

,Created Date,Complaint Type,Descriptor,Incident Zip,City,Borough,Vehicle Type
19,03/20/2025 03:32:00 PM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11222.0,BROOKLYN,BROOKLYN,NaN
39,03/20/2025 05:41:00 AM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11222.0,BROOKLYN,BROOKLYN,NaN
75,03/19/2025 10:32:00 AM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11222.0,BROOKLYN,BROOKLYN,NaN
258,03/14/2025 01:23:00 PM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11222.0,BROOKLYN,BROOKLYN,NaN
343,03/12/2025 04:39:32 PM,Noise - Vehicle,Engine Idling,11222.0,BROOKLYN,BROOKLYN,SUV
...,...,...,...,...,...,...,...
137922,01/16/2015 09:49:24 AM,Noise - Vehicle,Engine Idling,11222.0,BROOKLYN,BROOKLYN,NaN
137923,01/16/2015 09:37:50 AM,Noise - Vehicle,Engine Idling,11222.0,BROOKLYN,BROOKLYN,NaN
137979,01/13/2015 10:31:00 PM,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",11222.0,BROOKLYN,BROOKLYN,NaN
138056,01/09/2015 10:12:39 PM,Noise - Vehicle,Engine Idling,11222.0,BROOKLYN,BROOKLYN,NaN
138147,01/05/2015 11:50:10 AM,Noise - Vehicle,Engine Idling,11222.0,BROOKLYN,BROOKLYN,NaN

In [297]:
## GREENPOINT
df[columns_to_display].query("`Incident Zip` == '11222.0'").value_counts("City")

City
BROOKLYN    2118
Name: count, dtype: int64

In [303]:
df[columns_to_display].query("`Incident Zip` == '11222.0'").value_counts("Vehicle Type")

Vehicle Type
Truck    55
Car      51
Other    24
SUV       3
Van       1
Name: count, dtype: int64

In [305]:
## ## has 1 'no idling' which are complaints about the sign, not actual idling- so total complaints should be counted as 2207

df[columns_to_display].query("`Incident Zip` == '11222.0'").value_counts("Descriptor")

Descriptor
Engine Idling                            1473
Air: Odor/Fumes, Vehicle Idling (AD3)     733
Idling or Blocking Traffic                  1
No Idling                                   1
Name: count, dtype: int64